version: 2
updates:
  - package-ecosystem: "pip"
    directory: /
    schedule:
      interval: "weekly"
      day: saturday
      time: "09:00"
      timezone: Asia/Kolkata
    # Assignees to set on pull requests
    assignees:
      - "githubofkrishnadhas"
    # prefix specifies a prefix for all commit messages. When you specify a prefix for commit messages,
    # GitHub will automatically add a colon between the defined prefix and the commit message provided the
    # defined prefix ends with a letter, number, closing parenthesis, or closing bracket.
    commit-message:
      prefix: "dependabot python package"
    # Use reviewers to specify individual reviewers or teams of reviewers for all pull requests raised for a package manager.
    reviewers:
      - "devwithkrishna/admin"
    # Raise pull requests for version updates to pip against the `main` branch
    target-branch: "main"
    # Labels on pull requests for version updates only
    labels:
      - "pip dependencies"
    # Increase the version requirements for Composer only when required
    versioning-strategy: increase-if-necessary
    # Dependabot opens a maximum of five pull requests for version updates. Once there are five open pull requests from Dependabot,
    # Dependabot will not open any new requests until some of those open requests are merged or closed.
    # Use open-pull-requests-limit to change this limit.
    open-pull-requests-limit: 10